# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AnimalCountMetric(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_distinct_animals': 'float',
        'dates': 'list[AnimalCountMetricDates]',
        'animal_type': 'AnimalType'
    }

    attribute_map = {
        'total_distinct_animals': 'total_distinct_animals',
        'dates': 'dates',
        'animal_type': 'animal_type'
    }

    def __init__(self, total_distinct_animals=None, dates=None, animal_type=None):  # noqa: E501
        """AnimalCountMetric - a model defined in Swagger"""  # noqa: E501
        self._total_distinct_animals = None
        self._dates = None
        self._animal_type = None
        self.discriminator = None
        if total_distinct_animals is not None:
            self.total_distinct_animals = total_distinct_animals
        if dates is not None:
            self.dates = dates
        if animal_type is not None:
            self.animal_type = animal_type

    @property
    def total_distinct_animals(self):
        """Gets the total_distinct_animals of this AnimalCountMetric.  # noqa: E501


        :return: The total_distinct_animals of this AnimalCountMetric.  # noqa: E501
        :rtype: float
        """
        return self._total_distinct_animals

    @total_distinct_animals.setter
    def total_distinct_animals(self, total_distinct_animals):
        """Sets the total_distinct_animals of this AnimalCountMetric.


        :param total_distinct_animals: The total_distinct_animals of this AnimalCountMetric.  # noqa: E501
        :type: float
        """

        self._total_distinct_animals = total_distinct_animals

    @property
    def dates(self):
        """Gets the dates of this AnimalCountMetric.  # noqa: E501


        :return: The dates of this AnimalCountMetric.  # noqa: E501
        :rtype: list[AnimalCountMetricDates]
        """
        return self._dates

    @dates.setter
    def dates(self, dates):
        """Sets the dates of this AnimalCountMetric.


        :param dates: The dates of this AnimalCountMetric.  # noqa: E501
        :type: list[AnimalCountMetricDates]
        """

        self._dates = dates

    @property
    def animal_type(self):
        """Gets the animal_type of this AnimalCountMetric.  # noqa: E501


        :return: The animal_type of this AnimalCountMetric.  # noqa: E501
        :rtype: AnimalType
        """
        return self._animal_type

    @animal_type.setter
    def animal_type(self, animal_type):
        """Sets the animal_type of this AnimalCountMetric.


        :param animal_type: The animal_type of this AnimalCountMetric.  # noqa: E501
        :type: AnimalType
        """

        self._animal_type = animal_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnimalCountMetric, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnimalCountMetric):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
