# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AnimalCountMetricDates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'date',
        'distinct_animals_for_date': 'date'
    }

    attribute_map = {
        '_date': 'date',
        'distinct_animals_for_date': 'distinct_animals_for_date'
    }

    def __init__(self, _date=None, distinct_animals_for_date=None):  # noqa: E501
        """AnimalCountMetricDates - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._distinct_animals_for_date = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if distinct_animals_for_date is not None:
            self.distinct_animals_for_date = distinct_animals_for_date

    @property
    def _date(self):
        """Gets the _date of this AnimalCountMetricDates.  # noqa: E501


        :return: The _date of this AnimalCountMetricDates.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this AnimalCountMetricDates.


        :param _date: The _date of this AnimalCountMetricDates.  # noqa: E501
        :type: date
        """

        self.__date = _date

    @property
    def distinct_animals_for_date(self):
        """Gets the distinct_animals_for_date of this AnimalCountMetricDates.  # noqa: E501


        :return: The distinct_animals_for_date of this AnimalCountMetricDates.  # noqa: E501
        :rtype: date
        """
        return self._distinct_animals_for_date

    @distinct_animals_for_date.setter
    def distinct_animals_for_date(self, distinct_animals_for_date):
        """Sets the distinct_animals_for_date of this AnimalCountMetricDates.


        :param distinct_animals_for_date: The distinct_animals_for_date of this AnimalCountMetricDates.  # noqa: E501
        :type: date
        """

        self._distinct_animals_for_date = distinct_animals_for_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnimalCountMetricDates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnimalCountMetricDates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
