# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AnimalWithDailysSubSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'todays_enrichments': 'list[EnrichmentSession]',
        'todays_evaluations': 'list[Evaluation]'
    }

    attribute_map = {
        'todays_enrichments': 'todaysEnrichments',
        'todays_evaluations': 'todaysEvaluations'
    }

    def __init__(self, todays_enrichments=None, todays_evaluations=None):  # noqa: E501
        """AnimalWithDailysSubSchema - a model defined in Swagger"""  # noqa: E501
        self._todays_enrichments = None
        self._todays_evaluations = None
        self.discriminator = None
        if todays_enrichments is not None:
            self.todays_enrichments = todays_enrichments
        if todays_evaluations is not None:
            self.todays_evaluations = todays_evaluations

    @property
    def todays_enrichments(self):
        """Gets the todays_enrichments of this AnimalWithDailysSubSchema.  # noqa: E501


        :return: The todays_enrichments of this AnimalWithDailysSubSchema.  # noqa: E501
        :rtype: list[EnrichmentSession]
        """
        return self._todays_enrichments

    @todays_enrichments.setter
    def todays_enrichments(self, todays_enrichments):
        """Sets the todays_enrichments of this AnimalWithDailysSubSchema.


        :param todays_enrichments: The todays_enrichments of this AnimalWithDailysSubSchema.  # noqa: E501
        :type: list[EnrichmentSession]
        """

        self._todays_enrichments = todays_enrichments

    @property
    def todays_evaluations(self):
        """Gets the todays_evaluations of this AnimalWithDailysSubSchema.  # noqa: E501


        :return: The todays_evaluations of this AnimalWithDailysSubSchema.  # noqa: E501
        :rtype: list[Evaluation]
        """
        return self._todays_evaluations

    @todays_evaluations.setter
    def todays_evaluations(self, todays_evaluations):
        """Sets the todays_evaluations of this AnimalWithDailysSubSchema.


        :param todays_evaluations: The todays_evaluations of this AnimalWithDailysSubSchema.  # noqa: E501
        :type: list[Evaluation]
        """

        self._todays_evaluations = todays_evaluations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnimalWithDailysSubSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnimalWithDailysSubSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
