# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AnumberArray(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'a_number': 'SubAnumberArray'
    }

    attribute_map = {
        'a_number': 'aNumber'
    }

    def __init__(self, a_number=None):  # noqa: E501
        """AnumberArray - a model defined in Swagger"""  # noqa: E501
        self._a_number = None
        self.discriminator = None
        if a_number is not None:
            self.a_number = a_number

    @property
    def a_number(self):
        """Gets the a_number of this AnumberArray.  # noqa: E501


        :return: The a_number of this AnumberArray.  # noqa: E501
        :rtype: SubAnumberArray
        """
        return self._a_number

    @a_number.setter
    def a_number(self, a_number):
        """Sets the a_number of this AnumberArray.


        :param a_number: The a_number of this AnumberArray.  # noqa: E501
        :type: SubAnumberArray
        """

        self._a_number = a_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnumberArray, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnumberArray):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
