# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class NewEnrichmentSession(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'is_long_stay': 'bool',
        'has_training_plan': 'bool',
        'returned': 'datetime',
        'depart': 'datetime',
        'walker_name': 'str',
        'location_at_time_of_enrichment': 'str',
        'color_code_at_time_of_enrichment': 'str',
        'animal': 'int',
        'human_type': 'int',
        'enrichment_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'is_long_stay': 'isLongStay',
        'has_training_plan': 'hasTrainingPlan',
        'returned': 'returned',
        'depart': 'depart',
        'walker_name': 'walkerName',
        'location_at_time_of_enrichment': 'locationAtTimeOfEnrichment',
        'color_code_at_time_of_enrichment': 'colorCodeAtTimeOfEnrichment',
        'animal': 'animal',
        'human_type': 'humanType',
        'enrichment_type': 'enrichmentType'
    }

    def __init__(self, id=None, is_long_stay=None, has_training_plan=None, returned=None, depart=None, walker_name=None, location_at_time_of_enrichment=None, color_code_at_time_of_enrichment=None, animal=None, human_type=None, enrichment_type=None):  # noqa: E501
        """NewEnrichmentSession - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_long_stay = None
        self._has_training_plan = None
        self._returned = None
        self._depart = None
        self._walker_name = None
        self._location_at_time_of_enrichment = None
        self._color_code_at_time_of_enrichment = None
        self._animal = None
        self._human_type = None
        self._enrichment_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.is_long_stay = is_long_stay
        self.has_training_plan = has_training_plan
        self.returned = returned
        self.depart = depart
        self.walker_name = walker_name
        self.location_at_time_of_enrichment = location_at_time_of_enrichment
        if color_code_at_time_of_enrichment is not None:
            self.color_code_at_time_of_enrichment = color_code_at_time_of_enrichment
        if animal is not None:
            self.animal = animal
        if human_type is not None:
            self.human_type = human_type
        if enrichment_type is not None:
            self.enrichment_type = enrichment_type

    @property
    def id(self):
        """Gets the id of this NewEnrichmentSession.  # noqa: E501


        :return: The id of this NewEnrichmentSession.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NewEnrichmentSession.


        :param id: The id of this NewEnrichmentSession.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def is_long_stay(self):
        """Gets the is_long_stay of this NewEnrichmentSession.  # noqa: E501


        :return: The is_long_stay of this NewEnrichmentSession.  # noqa: E501
        :rtype: bool
        """
        return self._is_long_stay

    @is_long_stay.setter
    def is_long_stay(self, is_long_stay):
        """Sets the is_long_stay of this NewEnrichmentSession.


        :param is_long_stay: The is_long_stay of this NewEnrichmentSession.  # noqa: E501
        :type: bool
        """
        if is_long_stay is None:
            raise ValueError("Invalid value for `is_long_stay`, must not be `None`")  # noqa: E501

        self._is_long_stay = is_long_stay

    @property
    def has_training_plan(self):
        """Gets the has_training_plan of this NewEnrichmentSession.  # noqa: E501


        :return: The has_training_plan of this NewEnrichmentSession.  # noqa: E501
        :rtype: bool
        """
        return self._has_training_plan

    @has_training_plan.setter
    def has_training_plan(self, has_training_plan):
        """Sets the has_training_plan of this NewEnrichmentSession.


        :param has_training_plan: The has_training_plan of this NewEnrichmentSession.  # noqa: E501
        :type: bool
        """
        if has_training_plan is None:
            raise ValueError("Invalid value for `has_training_plan`, must not be `None`")  # noqa: E501

        self._has_training_plan = has_training_plan

    @property
    def returned(self):
        """Gets the returned of this NewEnrichmentSession.  # noqa: E501


        :return: The returned of this NewEnrichmentSession.  # noqa: E501
        :rtype: datetime
        """
        return self._returned

    @returned.setter
    def returned(self, returned):
        """Sets the returned of this NewEnrichmentSession.


        :param returned: The returned of this NewEnrichmentSession.  # noqa: E501
        :type: datetime
        """
        if returned is None:
            raise ValueError("Invalid value for `returned`, must not be `None`")  # noqa: E501

        self._returned = returned

    @property
    def depart(self):
        """Gets the depart of this NewEnrichmentSession.  # noqa: E501


        :return: The depart of this NewEnrichmentSession.  # noqa: E501
        :rtype: datetime
        """
        return self._depart

    @depart.setter
    def depart(self, depart):
        """Sets the depart of this NewEnrichmentSession.


        :param depart: The depart of this NewEnrichmentSession.  # noqa: E501
        :type: datetime
        """
        if depart is None:
            raise ValueError("Invalid value for `depart`, must not be `None`")  # noqa: E501

        self._depart = depart

    @property
    def walker_name(self):
        """Gets the walker_name of this NewEnrichmentSession.  # noqa: E501


        :return: The walker_name of this NewEnrichmentSession.  # noqa: E501
        :rtype: str
        """
        return self._walker_name

    @walker_name.setter
    def walker_name(self, walker_name):
        """Sets the walker_name of this NewEnrichmentSession.


        :param walker_name: The walker_name of this NewEnrichmentSession.  # noqa: E501
        :type: str
        """
        if walker_name is None:
            raise ValueError("Invalid value for `walker_name`, must not be `None`")  # noqa: E501

        self._walker_name = walker_name

    @property
    def location_at_time_of_enrichment(self):
        """Gets the location_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501


        :return: The location_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501
        :rtype: str
        """
        return self._location_at_time_of_enrichment

    @location_at_time_of_enrichment.setter
    def location_at_time_of_enrichment(self, location_at_time_of_enrichment):
        """Sets the location_at_time_of_enrichment of this NewEnrichmentSession.


        :param location_at_time_of_enrichment: The location_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501
        :type: str
        """
        if location_at_time_of_enrichment is None:
            raise ValueError("Invalid value for `location_at_time_of_enrichment`, must not be `None`")  # noqa: E501

        self._location_at_time_of_enrichment = location_at_time_of_enrichment

    @property
    def color_code_at_time_of_enrichment(self):
        """Gets the color_code_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501


        :return: The color_code_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501
        :rtype: str
        """
        return self._color_code_at_time_of_enrichment

    @color_code_at_time_of_enrichment.setter
    def color_code_at_time_of_enrichment(self, color_code_at_time_of_enrichment):
        """Sets the color_code_at_time_of_enrichment of this NewEnrichmentSession.


        :param color_code_at_time_of_enrichment: The color_code_at_time_of_enrichment of this NewEnrichmentSession.  # noqa: E501
        :type: str
        """

        self._color_code_at_time_of_enrichment = color_code_at_time_of_enrichment

    @property
    def animal(self):
        """Gets the animal of this NewEnrichmentSession.  # noqa: E501


        :return: The animal of this NewEnrichmentSession.  # noqa: E501
        :rtype: int
        """
        return self._animal

    @animal.setter
    def animal(self, animal):
        """Sets the animal of this NewEnrichmentSession.


        :param animal: The animal of this NewEnrichmentSession.  # noqa: E501
        :type: int
        """

        self._animal = animal

    @property
    def human_type(self):
        """Gets the human_type of this NewEnrichmentSession.  # noqa: E501


        :return: The human_type of this NewEnrichmentSession.  # noqa: E501
        :rtype: int
        """
        return self._human_type

    @human_type.setter
    def human_type(self, human_type):
        """Sets the human_type of this NewEnrichmentSession.


        :param human_type: The human_type of this NewEnrichmentSession.  # noqa: E501
        :type: int
        """

        self._human_type = human_type

    @property
    def enrichment_type(self):
        """Gets the enrichment_type of this NewEnrichmentSession.  # noqa: E501


        :return: The enrichment_type of this NewEnrichmentSession.  # noqa: E501
        :rtype: str
        """
        return self._enrichment_type

    @enrichment_type.setter
    def enrichment_type(self, enrichment_type):
        """Sets the enrichment_type of this NewEnrichmentSession.


        :param enrichment_type: The enrichment_type of this NewEnrichmentSession.  # noqa: E501
        :type: str
        """

        self._enrichment_type = enrichment_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NewEnrichmentSession, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewEnrichmentSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
