# coding: utf-8

"""
    The Enrichment List

    The THS enrichment list  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contactme@markwilkins.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SortableLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'SortDirection',
        'name': 'SortDirection',
        'bio_security': 'SortDirection',
        'ordinal': 'SortDirection'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'bio_security': 'bioSecurity',
        'ordinal': 'ordinal'
    }

    def __init__(self, id=None, name=None, bio_security=None, ordinal=None):  # noqa: E501
        """SortableLocation - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._bio_security = None
        self._ordinal = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if bio_security is not None:
            self.bio_security = bio_security
        if ordinal is not None:
            self.ordinal = ordinal

    @property
    def id(self):
        """Gets the id of this SortableLocation.  # noqa: E501


        :return: The id of this SortableLocation.  # noqa: E501
        :rtype: SortDirection
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SortableLocation.


        :param id: The id of this SortableLocation.  # noqa: E501
        :type: SortDirection
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SortableLocation.  # noqa: E501


        :return: The name of this SortableLocation.  # noqa: E501
        :rtype: SortDirection
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SortableLocation.


        :param name: The name of this SortableLocation.  # noqa: E501
        :type: SortDirection
        """

        self._name = name

    @property
    def bio_security(self):
        """Gets the bio_security of this SortableLocation.  # noqa: E501


        :return: The bio_security of this SortableLocation.  # noqa: E501
        :rtype: SortDirection
        """
        return self._bio_security

    @bio_security.setter
    def bio_security(self, bio_security):
        """Sets the bio_security of this SortableLocation.


        :param bio_security: The bio_security of this SortableLocation.  # noqa: E501
        :type: SortDirection
        """

        self._bio_security = bio_security

    @property
    def ordinal(self):
        """Gets the ordinal of this SortableLocation.  # noqa: E501


        :return: The ordinal of this SortableLocation.  # noqa: E501
        :rtype: SortDirection
        """
        return self._ordinal

    @ordinal.setter
    def ordinal(self, ordinal):
        """Sets the ordinal of this SortableLocation.


        :param ordinal: The ordinal of this SortableLocation.  # noqa: E501
        :type: SortDirection
        """

        self._ordinal = ordinal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SortableLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SortableLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
